# -*- coding: utf-8 -*-
"""schedule-assistant.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19OqyesWGW_8X7rh--mFTUAdP5f8GpICp
"""
 

import os
from getpass import getpass

os.environ["GEMINI_API_KEY"] = getpass("Enter your Gemini API Key: ")

from datetime import date, timedelta

today = date.today()

schedule = [
    {
        "id": "event_1",
        "date": str(today + timedelta(days=1)),
        "time": "10:00 AM",
        "title": "Team Meeting",
        "type": "meeting",
        "description": "Discuss project progress and assign tasks."
    },
    {
        "id": "event_2",
        "date": str(today + timedelta(days=2)),
        "time": "02:00 PM",
        "title": "AI Workshop",
        "type": "workshop",
        "description": "Learn about Agentic AI and RAG."
    },
    {
        "id": "event_3",
        "date": str(today + timedelta(days=3)),
        "time": "09:30 AM",
        "title": "Doctor Appointment",
        "type": "appointment",
        "description": "Regular health checkup."
    },
    {
        "id": "event_4",
        "date": str(today + timedelta(days=4)),
        "time": "05:00 PM",
        "title": "Complete Assignment",
        "type": "task",
        "description": "Finish and submit the workshop assignment."
    },
    {
        "id": "event_5",
        "date": str(today + timedelta(days=5)),
        "time": "11:00 AM",
        "title": "Project Review",
        "type": "meeting",
        "description": "Review the current project."
    },
    {
        "id": "event_6",
        "date": str(today + timedelta(days=7)),
        "time": "03:00 PM",
        "title": "Python Practice",
        "type": "task",
        "description": "Practice Python programming problems."
    },
    {
        "id": "event_7",
        "date": str(today + timedelta(days=10)),
        "time": "10:30 AM",
        "title": "Cloud Computing Workshop",
        "type": "workshop",
        "description": "Learn cloud computing and deployment."
    },
    {
        "id": "event_8",
        "date": str(today + timedelta(days=12)),
        "time": "01:00 PM",
        "title": "Client Meeting",
        "type": "meeting",
        "description": "Discuss project requirements with the client."
    },
    {
        "id": "event_9",
        "date": str(today + timedelta(days=15)),
        "time": "04:00 PM",
        "title": "Database Assignment",
        "type": "task",
        "description": "Complete SQL and database assignment."
    },
    {
        "id": "event_10",
        "date": str(today + timedelta(days=20)),
        "time": "11:00 AM",
        "title": "Career Guidance Session",
        "type": "appointment",
        "description": "Career and resume guidance."
    }
]

print("Schedule created successfully!")
print("Number of events:", len(schedule))

import chromadb
from google import genai

# Connect to Gemini
client = genai.Client(
    api_key=os.environ["GEMINI_API_KEY"]
)

# Create ChromaDB client
chroma_client = chromadb.Client()

# Create a collection for our schedule
collection = chroma_client.get_or_create_collection(
    name="schedule"
)

print("ChromaDB created successfully!")

for event in schedule:

    # Convert the event into searchable text
    text = f"""
    Date: {event['date']}
    Time: {event['time']}
    Title: {event['title']}
    Type: {event['type']}
    Description: {event['description']}
    """

    # Create an embedding using Gemini
    result = client.models.embed_content(
        model="gemini-embedding-001",
        contents=text
    )

    embedding = result.embeddings[0].values

    # Store the event in ChromaDB
    collection.add(
        ids=[event["id"]],
        documents=[text],
        embeddings=[embedding],
        metadatas=[event]
    )

print("All schedule events stored in ChromaDB!")

for event in schedule:

    text = f"""
    Date: {event['date']}
    Time: {event['time']}
    Title: {event['title']}
    Type: {event['type']}
    Description: {event['description']}
    """

    result = client.models.embed_content(
        model="gemini-embedding-001",
        contents=text
    )

    embedding = result.embeddings[0].values

    collection.add(
        ids=[event["id"]],
        documents=[text],
        embeddings=[embedding],
        metadatas=[event]
    )

print("All schedule events stored in ChromaDB!")

def get_schedule(query):

    # Convert user query into an embedding
    result = client.models.embed_content(
        model="gemini-embedding-001",
        contents=query
    )

    query_embedding = result.embeddings[0].values

    # Search ChromaDB
    results = collection.query(
        query_embeddings=[query_embedding],
        n_results=5
    )

    if not results["documents"]:
        return "No matching schedule found."

    schedule_results = []

    for i, document in enumerate(results["documents"][0]):

        metadata = results["metadatas"][0][i]

        event_id = metadata.get("id", "unknown")

        schedule_results.append(
            f"""
Event ID: {event_id}

{document}
"""
        )

    return "\n\n".join(schedule_results)

result = get_schedule( "What workshops are scheduled?")

print(result)

def rebuild_chroma():

    global collection

    # Delete the old ChromaDB collection
    try:
        chroma_client.delete_collection("schedule")
    except:
        pass

    # Create a new collection
    collection = chroma_client.get_or_create_collection(
        name="schedule"
    )

    # Store all current schedule events again
    for event in schedule:

        text = f"""
        Date: {event['date']}
        Time: {event['time']}
        Title: {event['title']}
        Type: {event['type']}
        Description: {event['description']}
        """

        result = client.models.embed_content(
            model="gemini-embedding-001",
            contents=text
        )

        embedding = result.embeddings[0].values

        collection.add(
            ids=[event["id"]],
            documents=[text],
            embeddings=[embedding],
            metadatas=[event]
        )

    print("ChromaDB updated successfully!")

def update_schedule(
    action,
    event_id=None,
    date_value=None,
    time_value=None,
    title=None,
    event_type=None,
    description=None
):

    global schedule

    # ADD
    if action == "add":

        new_id = f"event_{len(schedule) + 1}"

        new_event = {
            "id": new_id,
            "date": date_value,
            "time": time_value,
            "title": title,
            "type": event_type or "task",
            "description": description or ""
        }

        schedule.append(new_event)

        rebuild_chroma()

        return (
            f"Added '{title}' on "
            f"{date_value} at {time_value}."
        )

    # UPDATE
    elif action == "update":

        event = next(
            (e for e in schedule if e["id"] == event_id),
            None
        )

        if not event:
            return "Event not found."

        if date_value:
            event["date"] = date_value

        if time_value:
            event["time"] = time_value

        if title:
            event["title"] = title

        if event_type:
            event["type"] = event_type

        if description:
            event["description"] = description

        rebuild_chroma()

        return (
            f"Updated '{event['title']}'. "
            f"New time: {event['date']} at {event['time']}."
        )

    # DELETE
    elif action == "delete":

        event = next(
            (e for e in schedule if e["id"] == event_id),
            None
        )

        if not event:
            return "Event not found."

        schedule.remove(event)

        rebuild_chroma()

        return f"Deleted '{event['title']}'."

    return "Invalid action."

result = update_schedule(
    action="add",
    date_value="2026-08-25",
    time_value="03:00 PM",
    title="New Team Meeting",
    event_type="meeting",
    description="Discuss project progress."
)

print(result)

tools = [
    {
        "function_declarations": [
            {
                "name": "get_schedule",
                "description": "Retrieve relevant schedule information based on the user's date, time, event type, or question.",
                "parameters": {
                    "type": "OBJECT",
                    "properties": {
                        "query": {
                            "type": "STRING",
                            "description": "The user's schedule-related question."
                        }
                    },
                    "required": ["query"]
                }
            },
            {
                "name": "update_schedule",
                "description": "Add, update, or delete schedule events.",
                "parameters": {
                    "type": "OBJECT",
                    "properties": {
                        "action": {
                            "type": "STRING",
                            "enum": ["add", "update", "delete"],
                            "description": "The action to perform."
                        },
                        "event_id": {
                            "type": "STRING",
                            "description": "ID of the event to update or delete."
                        },
                        "date_value": {
                            "type": "STRING",
                            "description": "Date of the event."
                        },
                        "time_value": {
                            "type": "STRING",
                            "description": "Time of the event."
                        },
                        "title": {
                            "type": "STRING",
                            "description": "Title of the event."
                        },
                        "event_type": {
                            "type": "STRING",
                            "description": "Type of event such as meeting, workshop, task, or appointment."
                        },
                        "description": {
                            "type": "STRING",
                            "description": "Description of the event."
                        }
                    },
                    "required": ["action"]
                }
            }
        ]
    }
]

print("Agent tools created!")

def ask_agent(user_query):

    response = client.models.generate_content(
        model="gemini-3.5-flash-lite",
        contents=user_query,
        config={
            "tools": tools,
            "system_instruction": """
You are an intelligent Agentic Schedule Assistant.

You manage the user's schedule for the next 30 days.

Use get_schedule when:
- The user asks about existing events.
- The user asks what is scheduled.
- The user asks about meetings, workshops, tasks, or appointments.
- The user asks whether they are free.

Use update_schedule when:
- The user wants to add an event.
- The user wants to update an event.
- The user wants to move an event.
- The user wants to delete an event.

For moving or changing an existing event:
1. First retrieve the existing event using get_schedule.
2. Then update it using update_schedule.

Never invent schedule information.

Keep answers short and clear.
"""
        }
    )

    return response

response = ask_agent(
    "What meetings do I have?"
)

print(response.text)

from google.genai import types

def run_agent(user_query):

    contents = [
        types.Content(
            role="user",
            parts=[
                types.Part.from_text(text=user_query)
            ]
        )
    ]

    # Allow multiple tool calls
    for step in range(5):

        response = client.models.generate_content(
            model="gemini-3.1-flash-lite",
            contents=contents,
            config={
                "tools": tools,
                "system_instruction": """
You are an Agentic Schedule Assistant.

You manage the user's schedule for the next 30 days.

Use get_schedule when the user asks about:
- existing events
- meetings
- workshops
- tasks
- appointments
- free time

Use update_schedule when the user wants to:
- add an event
- update an event
- move an event
- delete an event

For moving, updating, or deleting an existing event:
1. First use get_schedule.
2. Find the correct Event ID.
3. Then use update_schedule with that Event ID.
4. Give a short confirmation.

Never invent schedule information.
Keep answers short and clear.
"""
            }
        )

        # No tool required
        if not response.function_calls:
            return response.text

        # Add Gemini response
        contents.append(
            response.candidates[0].content
        )

        # Execute tools
        for function_call in response.function_calls:

            print("Tool selected:", function_call.name)
            print("Arguments:", function_call.args)

            if function_call.name == "get_schedule":

                result = get_schedule(
                    function_call.args["query"]
                )

            elif function_call.name == "update_schedule":

                result = update_schedule(
                    action=function_call.args.get("action"),
                    event_id=function_call.args.get("event_id"),
                    date_value=function_call.args.get("date_value"),
                    time_value=function_call.args.get("time_value"),
                    title=function_call.args.get("title"),
                    event_type=function_call.args.get("event_type"),
                    description=function_call.args.get("description")
                )

            else:
                result = "Unknown tool."

            print("Tool result:", result)

            # Send tool result back to Gemini
            function_response = types.Part.from_function_response(
                name=function_call.name,
                response={
                    "result": result
                }
            )

            contents.append(
                types.Content(
                    role="user",
                    parts=[function_response]
                )
            )

    return "I could not complete the request."

answer = run_agent("What meetings do I have?")
print(answer)

answer = run_agent(
    "Add a meeting on August 25 at 3 PM called Team Discussion."
)

print(answer)

answer = run_agent(
    "Move my Team Meeting from 10 AM to 4 PM."
)

print(answer)

answer = run_agent(
    "Move my Team Meeting from 10 AM to 4 PM."
)

print(answer)

answer = run_agent(
    "Delete my Team Discussion meeting."
)

print(answer)

print("TEST 1")
print(run_agent("What do I have scheduled tomorrow?"))

print("\n" + "="*50)

print("TEST 2")
print(run_agent("What workshops do I have?"))

print("\n" + "="*50)

print("TEST 3")
print(run_agent("Am I free tomorrow afternoon?"))

print("\n" + "="*50)

print("TEST 4")
print(run_agent("Add a meeting on August 28 at 3 PM called Project Meeting."))
